# Generated by Django 3.0.1 on 2020-01-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcher_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(choices=[('CA', 'Campus Ambassador'), ('P', 'Participant'), ('W', 'Winner')], default='CA', max_length=30)),
                ('is_generated', models.BooleanField(default=None)),
                ('is_valid', models.BooleanField(default=None)),
                ('certificate_url', models.BooleanField(blank=True, default=None)),
            ],
        ),
    ]
