# Generated by Django 3.0.1 on 2020-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='certificate_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
