CERTIFICATE_OPTIONS = [
        ('CA', 'Campus Ambassador'),
        ('P' , 'Participant' ),
        ('W' , 'Winner'),
    ]

EVENT_OPTIONS = [
        ('Live Sketching' , 'Live Sketching'),
        ('Clay Modelling' , 'Clay Modelling'),
        ('Who is it?' , 'Who is it?'),
        ('Ink the tee' , 'Ink the tee'),
        ('Face Art' , 'Face Art'),
        ('Rangoli' , 'Rangoli'),
        ('Graffiti' , 'Graffiti'),
        ('Best Adj, Best Speaker' , 'Best Adj, Best Speaker'),
        ('Poetry-Hindi' , 'Poetry-Hindi'),
        ('Poetry-English' , 'Poetry-English'),
        ('Zephyr' , 'Zephyr'),
        ('Mehfil' , 'Mehfil'),
        ('JAM' , 'JAM'),
        ('50n5' , '50n5'),
        ('Arm Wrestling' , 'Arm Wrestling'),
        ('Gully' , 'Gully'),
        ('3vs3 Basket' , '3vs3 Basket'),
        ('3vs3 Volley' , '3vs3 Volley'),
        ('Diva/Hunk' , 'Diva/Hunk'),
        ('Snapthriilz' , 'Snapthriilz'),
        ("Director's Cut" , 'Directors Cut'),
        ('Custom Brush' , 'Custom Brush'),
        ('Doodle Pad' , 'Doodle Pad'),
        ('General Quiz' , 'General Quiz'),
        ('Business Quiz' , 'Business Quiz'),
        ('Sports Quiz' , 'Sports Quiz'),
        ('Bollywood Quiz' , 'Bollywood Quiz'),
        ('Electric Heels', 'Electric Heels'),
        ('Step up' , 'Step up'),
        ('SUTUCD' , 'SUTUCD'),
        ('Dancing Duo' , 'Dancing Duo'),
        ('Navras' , 'Navras'),
        ('Raga High' , 'Raga High'),
        ('VOA' , 'VOA'),
        ('Unplugged' , 'Unplugged'),
        ('Choir' , 'Choir'),
        ('Theatrix' , 'Theatrix'),
        ('Halla Bol' , 'Halla Bol'),
        ('Monodrama' , 'Monodrama'),
        ('Rap Battle' , 'Rap Battle'),
        ('Rocko' , 'Rocko'),
        ('Best performances and giv' , 'Best performances and giv'),
        ('Crossfade' , 'Crossfade'),
        ('AGT' , 'AGT'),
        ('Haute' , 'Haute'),
        ('State of Dress' , 'State of Dress'),
        ('Glamour Nova' , 'Glamour Nova'),
        ('None' , 'None'),
    ]